ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS vendor_type VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS addresses JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS bank_ifsc VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS bank_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS credit_days INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quality_rating NUMERIC(2, 1) NULL,
  ADD COLUMN IF NOT EXISTS payment_terms TEXT NULL;
